#!/bin/bash

#CHECK_HTTP="/usr/local/Cellar/nagios-plugins/2.0.3/sbin/check_http"
CHECK_HTTP="/usr/lib/nagios/plugins/check_http"
IFS=$'\n'

### check args
usage() {
cat << EOS
Usage: $ ${0} [CONFIG_FILE]
EOS
}

[ -z "${1}" ] && usage && exit 3

CONFIG_FILE=${1}

if [ -e ${CONFIG_FILE} ]; then
  source ${CONFIG_FILE}
else
  echo "[ERROR] Config file is not found." 2>&1
  exit 3
fi

if [ -z ${HOST_ADDRESS} ]; then
  HOST_DISABLE="On"
fi

### exec
status=0
err_list=()
ng=0

for domain in ${DOMAIN_LISTS[@]}; do
  if [ "${HOST_DISABLE}" = "On" ]; then
    HOST_ADDRESS=${domain}
  fi

  RES=`${CHECK_HTTP} --sni -H ${domain} -I ${HOST_ADDRESS} -C ${SSL_LIMIT}`
  exitcode=${?}
  echo "${RES} - [${domain}]"

  if [ ${exitcode} -ne 0 ]; then
    err_list+=(${RES})
    ng=$(( ng + 1 ))
    if [ ${exitcode} -gt ${status} ]; then
      status=${exitcode}
    fi
  fi
done

echo ""
if [ ${status} -eq 0 ]; then
  echo "***** ALL DOMAIN PASSED *****"
else
  echo "***** ERROR DOAMIN LIST *****" 2>&1
  echo "[ TOTAL: ${ng} ]" 2>&1
  for domain in ${err_list[@]}; do
    echo ${domain} 2>&1
  done
  echo "*****************************" 2>&1
fi

exit ${status}

