#!/bin/bash -u

HOST=$1
CHECK=~/bin/ip_check.sh
RESOLV="gk2"
source ~/.ssh/pass.conf

${CHECK} ${HOST} > /dev/null
if [ $? -ne 0 ]; then
  RES=`ssh ${RESOLV} "host ${HOST}"`
  if [ $? -ne 0 ]; then
    echo "[ERROR] invalid hostname."
    exit 1
  fi
  HOST=`echo ${RES} | awk '{print $4}'`
fi

expect -c "
set timeout 10
spawn ssh ${USER}@${HOST}
expect \"${USER}@${HOST}'s password\"; send \"${PASS}\n\"
 
interact
"

